code update
Plumsail/forms-templates pull request #1
Opened 2022-12-20 12:44 UTC by mnikitinaa

Code updates for Data table in Flowers order form

2022-12-21 09:21 UTC, jusper-dk commented
В код не должно быть таких моментов
![image](https://user-images.githubusercontent.com/27721442/208869349-ec4d8d37-d40d-491b-b41a-26280350d104.png)


И это не единственная форма, которую нужно поправить, ты можешь найти все формы поиском по файлам.

2022-12-21 12:29 UTC, mnikitinaa commented
console.log() убрала. Это единственная форма с таким кодом. Больше нигде нет Data Table с пред заполнением и расчетом общей стоимости.

2022-12-21 12:30 UTC, jusper-dk commented
> console.log() убрала. Это единственная форма с таким кодом. Больше нигде нет Data Table с пред заполнением и расчетом общей стоимости.

А эта?
https://plumsail.com/forms/templates/online-order-form/

2022-12-21 12:52 UTC, mnikitinaa commented
X__X Плохо искала. Тоже поправила.

2022-12-22 09:28 UTC, jusper-dk requested changes

2022-12-22 09:28 UTC, jusper-dk commented on Donation Form.json
> +  "js": "// donation to be paid\r\nvar donationAmount = 0.0;\r\n\r\nfunction highlightSelectedAmount() {\r\n    var buttons = document.getElementsByClassName('fd-donation-amount-button');\r\n    var
Ошибку можно и залоггировать. Старайся не править код автозаменой, ничего хорошего из этого не получается, как правило. Изменения в этом файле нужно откатить.

2022-12-22 11:28 UTC, mnikitinaa commented on Donation Form.json
> +  "js": "// donation to be paid\r\nvar donationAmount = 0.0;\r\n\r\nfunction highlightSelectedAmount() {\r\n    var buttons = document.getElementsByClassName('fd-donation-amount-button');\r\n    var
Поняла. Отменила изменения в Donation form.

2022-12-22 11:30 UTC, merged